<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-01-21 14:32

$extensionPath = t3lib_extMgm::extPath('wec_contentelements');
return array(
	'tx_weccontentelements_cobj' => $extensionPath . 'class.tx_weccontentelements_cobj.php',
	'tx_weccontentelements_getxmldata' => $extensionPath . 'class.tx_weccontentelements_getxmldata.php',
	'tx_weccontentelements_lib' => $extensionPath . 'class.tx_weccontentelements_lib.php',
);
?>